# Generated by Django 4.2.16 on 2024-09-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musician",
            options={"verbose_name": "Musician", "verbose_name_plural": "Musicians"},
        ),
    ]
